mex -O sub4.cpp
mex -O subdx.cpp
mex -O subdy.cpp
mex -O subdxx3.cpp
mex -O subdyy3.cpp
mex -O subdzz3.cpp
mex -O subdxy3.cpp
mex -O subdxz3.cpp
mex -O subdyz3.cpp
mex -O refinemx_2D.cpp
mex -O localmax_2D.cpp
mex -O refinemx_3D.cpp
mex -O localmax_3D.cpp
mex -O subdy3.cpp
mex -O subdz3.cpp
mex -O subdx3.cpp
mex -O subdxx.cpp
mex -O subdxy.cpp
mex -O subdyy.cpp
mex -O sub8.cpp